name: tag-and-release

on:
  push:
    branches:
      - main
    paths: 'setup.py'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Get version
      id: get_version
      run: |
        version=$(grep "version=" setup.py | cut -f2 -d"=" |tr -d "\""|tr -d ",")
        echo version=$version >> $GITHUB_OUTPUT
        echo version_tag=v$version >> $GITHUB_OUTPUT

    - name: Tag commit
      uses: tvdias/github-tagger@ed7350546e3e503b5e942dffd65bc8751a95e49d # v0.0.2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        tag: "${{steps.get_version.outputs.version_tag}}"

    - name: Extract from changelog
      id: extract_changes
      run: |
        # Must use a temporary file or it loses the formatting
        VERSION=${{steps.get_version.outputs.version}}; awk "/## \[$VERSION\]/{flag=1;next}/## \[/{flag=0}flag" CHANGELOG.md > REL-BODY.md

    - name: Create Relase TAR
      id: create_tar
      run: |
        mv github-secrets-manager.py github-secrets-manager
        tar cvzf ./github-secrets-manager-${{steps.get_version.outputs.version}}.tar.gz github-secrets-manager* requirements.txt setup.py README.md

    - name: Generate Checksum
      id: generate_checksum
      run: |
        checksum=$(sha256sum ./github-secrets-manager-${{steps.get_version.outputs.version}}.tar.gz | awk '{print $1}')
        echo "${checksum}" > sha256.sum
        echo "SHA256: ${checksum}" >> REL-BODY.md

    - name: Create Release
      uses: ncipollo/release-action@cdcc88a9acf3ca41c16c37bb7d21b9ad48560d87 # v1.15.0
      with:
        tag: ${{steps.get_version.outputs.version_tag}}
        artifacts: "github-secrets-manager*.tar.gz, sha256.sum"
        bodyFile: "REL-BODY.md"
        token: ${{ secrets.GITHUB_TOKEN }}
