name: Lint/Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      id-token: write
    env:
      PYTHON_VERSION: 3.9

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies
        run: pip install -r requirements-test.txt

      - name: Format
        uses: psf/black@stable

      - name: Test
        run:  |
          pytest --junitxml=pytest.xml --cov=. test*.py > pytest-coverage.txt

      - name: Comment coverage
        uses: MishaKav/pytest-coverage-comment@287292879eaaff04116f36d3eb1a670f6e5df1a4 # v1.7.1
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
