name: Lint/Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.9

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.1.6
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install Dependencies
        run: poetry install --no-interaction --no-root

      - name: Format
        run:  |
          source .venv/bin/activate
          poetry run black . --check

      - name: Lint
        run:  |
          source .venv/bin/activate
          poetry run pylint $(git ls-files '*.py') 

      - name: Test
        run:  |
          source .venv/bin/activate
          poetry run pytest -vv