name: Lint/Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      id-token: write
    env:
      PYTHON_VERSION: 3.9

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies
        run: pip install -r requirements-test.txt

      - name: Format
        uses: psf/black@stable

      - name: Test
        run:  |
          pytest --junitxml=pytest.xml --cov=. test*.py > pytest-coverage.txt

      - name: Comment coverage
        uses: MishaKav/pytest-coverage-comment@13d3c18e21895566c746187c9ea74736372e5e91 # v1.1.54
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
