name: Lint/Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.9

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies
        run: pip install -r requirements-test.txt

      - name: Format
        uses: psf/black@stable

      - name: Test
        run:  |
          pytest --junitxml=pytest.xml --cov=. test*.py > pytest-coverage.txt

      - name: Comment coverage
        uses: MishaKav/pytest-coverage-comment@fa1c641d7e3fa1d98ed95d5f658ccd638b774628 # v1.1.52
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
